fxamacker/ccf_draft

README.md
Add parentheses to CDDL to make order of precedence more obvious.
This change is a NOP and does not affect codecs.
Thanks @turbolent for [suggestions](https://www.notion.so/dapperlabs/Bastian-s-CCF-Draft-Notes-5d09fb1eefa740a0a36d1a9bafb06269) currently in notion.
=> Add parentheses to CDDL for readability

README.md
Fix formatting error introduced in last PR and bump revision.
There needs to be two spaces after a line for markdown to add a single newline.
=> Fix formatting error and bump revision

README.md
Use the CDDL naming convention specified in [Section 3.1 ](https://www.rfc-editor.org/rfc/rfc8610.html#section-3.1)of RFC 8610.
This PR does not make any other change to the CDDL.
=> Use CDDL naming convention specified in Section 3.1 in RFC 8610

README.md
Add `simple-type-id` in CDDL (about 105 lines).
Closes #2
=> Add simple type ID in CDDL

README.md
Add `value`,  `optional-value`, `array-value`, `dict-value`, `composite-value`, `link-value`, `path-value`, `capability-value`, `address-value`, and etc.
Closes #9
Closes #11
Closes #12
=> Add Cadence value encodings in CDDL

README.md
Fix `capability-type` encoding in CDDL by changing it from array to single data item.
Closes #23
=> Fix capability type encoding in CDDL

README.md
Use more consistent CDDL names.
Remove unused CBOR tag numbers.
=> Update CDDL to use more consistent naming, etc.

ccf_specs.md
=> Add Type Value encoding in CDDL

ccf_specs.md
Simplify CDDL choice by using CDDL group.  For more info, see  
https://www.rfc-editor.org/rfc/rfc8610.html#section-2.2.2.2
Thanks @turbolent for inspiring this update by mentioning enumerations during our 2nd CCF team meeting.
=> Simplify CDDL choice by using CDDL group

ccf_specs.md
Use array for capability type and also add more comments in the CDDL.
Thanks @turbolent for suggesting this in our 2nd CCF team meeting.
=> Use array for capability type

README.md
Add short description of Cadence with a link.
Add a Timeline section to show progress at a very high level.
=> Add info about Cadence and a Timeline section

ccf_specs.md
Closes #34
Added these type objects in CDDL:
- struct interface type
- resource interface type
- contract interface type
- reference type
- restricted type
Added interface types as options to ccf-composite-type-message.
Added reference and restricted types as options to inline-type.
Added support for function value.
Refactored CDDL to separate type objects from type value objects for readability and cleaner implementation.
Reassigned tag numbers to reserve some tag numbers in each (sub)group.  The following groups have assigned and reserved tag numbers [128, 255]:
- root objects:  2 of 8 are assigned
- types
- inline: 9 of 24 are assigned
- composite: 5 of 16 are assigned
- interface: 3 of 8 are assigned  
- type values
- non-composite and non-interface: 10 of 24 are assigned
- composite: …
=> Add more types and reassign tag numbers in CDDL

ccf_specs.md
Update CCF specs:
- Rename CCF Design section to Objectives.
- Make Objectives section at same level as Introduction.
- Update some text in the Introduction and Objectives sections.
- Add ", Inc." suffix to "Dapper Labs".
This PR does not affect CCF codec.
=> Rename CCF Design section to Objectives

README.md
These results are preliminary and subject to change.
=> Add preliminary size and benchmark comparisons to README

ccf_specs.md
Update text of CCF specs:
- Add section for Cadence types and `TypeValue` to describe why they are encoded differently.
- Add comment in CDDL about why interface-type doesn't have field info (it's not needed for decoding values implementing interface type).
This PR does not affect CCF codec.
Thanks @turbolent for suggesting addition of clarification/rationale about types vs type values while reviewing PR #35.
=> Clarify difference between Cadence type and TypeValue

README.md, ccf_specs.md
Update README:
- Provide separate status of CCF specs and CCF codec.
- Update Timeline to include milestones reached on Dec 9 and Dec 15.
- Add Next Steps under Status.
- Add note about more tests being required even though CCF codec passed all ported tests from JSON-Cadence Data Interchange Format.
- Add note about CCF codec eventually needing fuzz tests by the Cadence team before being used in production.
=> Update Status, Timeline, Next Steps

ccf_specs.md
Update ccf_specs.md to cite [section 6 of RFC 8949](https://datatracker.ietf.org/doc/html/rfc8949#name-converting-data-between-cbo) (CBOR) rather than RFC 8610 (CDDL) regarding conversion of data between CBOR and JSON.
=> Cite RFC 8949 section 6 for CBOR/JSON conversion

ccf_specs.md
Remove `link-value` because it is no longer exported from Cadence.
=> Remove link-value from CDDL

ccf_specs.md
Remove `path-domain` definition in CDDL to avoid making CCF too limiting.
=> Remove path-domain in CDDL

ccf_specs.md
This PR:
- Adds `ccf-typedef-and-value-message` as a top level message.  It encodes a Cadence value preceded by list of referenced type definitions.
- Refactors CDDL for easier reuse.
- Updates text to describe the new CCF message type and other changes.
Closes #50
=> Add a top level CCF message that combines a Cadence value with list of referenced type definitions

ccf_specs.md
Add ".ge 0" to `uint-value`, `uint128-value`, and `uint256-value`.
closes #52
=> Add constraints to uint values in CDDL

ccf_specs.md
Changes:
- Add boilerplate from RFC 8174 to define capitalized "MUST", "SHOULD", etc.
- Replace "this document" with "this specification" for consistency.
- Moved "Terminology" and "Objectives" sections under "Introduction" (like RFC 8949).
This PR does not affect codecs.
=> Update Terminology section and add RFC 8174 boilerplate

ccf_specs.md
Add Serialization Considerations section and specify
- Valid CCF Encoding Requirements
- Deterministic CCF Encoding Requirements
Replace "ABRIDGED DRAFT" with "DRAFT" in Status of this Document section.
These requirements are necessary and have an impact on CCF codec speed and memory use.
Prior formats (JSON-Cadence Data Interchange and CBF) didn't specify requirements for validity or deterministic encoding.  Updated benchmark comparisons (coming soon) should be viewed with this in mind.   For example, sorting (as part of deterministic encoding) isn't free.
=> Specify requirements for Valid and Deterministic Encodings

ccf_specs.md
The CCF Specification would not exist without Ramtin and Bastian.
=> Add Acknowledgements Section

README.md
Updated benchmarks using commit f911063 in https://github.com/onflow/cadence/pull/2364.
=> Update benchmark results in README

ccf_specs.md
Noticed this while reviewing https://github.com/onflow/cadence/pull/2364
- Restriction types may have no restrictions
- Composite values may have no fields
- Composite types may have no fields
There might be more cases that need to be fixed.
=> Fix multiplicities

ccf_specs.md
- Changed `composite-type.fields` from `+` to `*`.
- Changed `restricted-type-value.restrictions` from `+` to `*`.
Basically, this changes "one or more" to "zero or more" in order to be consistent with what was done in PR #66.
Updates https://github.com/onflow/cadence/pull/2364
Updates https://github.com/fxamacker/ccf_draft/pull/66
=> Fix more multiplicities by replacing CDDL representing "one or more" with "zero or more"

ccf_specs.md
In JSON-CDC, sometimes cadence-type-id was encoded when it was just a "stringification" of other encoded data and not necessary to encode.
In CCF, we don't need to keep this inefficiency for the sake of compatibility.
Thanks @turbolent for spotting this!
Removed the inefficiency by removing unnecessary cadence-type-id from
- restricted-type-value
- restricted-type
- function-value
Closes #68
=> Remove unnecessary cadence-type-id

ccf_specs.md
Cadence recently added `type-parameters` to `function-value`.  Update CCF to support it.
Closes #72
=> Add type-parameters to function-value in CDDL

ccf_specs.md
- Type parameter type bounds are optional
- Parameter argument labels are optional: they should be encoded as empty string if not given
=> Improve `function-value`

ccf_specs.md
We now explicitly specify nullable types starting with PR #75.  
- Remove null as an option for type-value.
- Specify null as an option for capability-type-value and restricted-type-value.
- Add valid requirement for unique name in function-type.type-parameters.
Thanks @turbolent for great suggestions during our discussions on Slack and for opening PR 75!
Closes #76
=> Remove nullable type-value and explicitly specify

ccf_specs.md
Update CDDL notation in CCF specs to:
- Allow type of restricted-type to be null.
- Allow borrow-type of capability-type to be null.
=> Allow null for capability and restricted type elem

ccf_specs.md
Update examples using hexadecimal and extended diagnostic notation to match recent changes in CDDL notation.
Closes #81
=> Update examples to match latest CDDL

ccf_specs.md
Update Why CBOR section's mention of fxamacker/cbor:
- Remove adjectives about it.
- Mention and link to [CCF codec in Cadence](https://github.com/onflow/cadence/tree/master/encoding/ccf).
- Mention and link to a [nonconfidential security assessment](https://github.com/veraison/go-cose/blob/v1.0.0-rc.1/reports/NCC_Microsoft-go-cose-Report_2022-05-26_v1.0.pdf) (NCC Group for Microsoft Corporation).
- Update usage stats because GitHub shows stats for v1 (obsolete version nobody should be using anymore).
=> Update text about fxamacker/cbor (CBOR codec)

ccf_specs.md
The CCF codec in Cadence is faster, uses less memory, encodes deterministically, and produces smaller encodings than the JSON-CDC codec.  A real FeesDeducted event taken from mainnet can encode to:
- 298 bytes in JSON-CDC (minified).
- 118 bytes in CCF (fully self-describing mode).
- ~20 bytes in CCF (partially self-describing mode).
And other updates to text that does not impact CCF codec.
=> Update text sections to not bury ledes

ccf_specs.md
CBOR is a modern alternative to earlier data formats such as JSON, GOB, MessagePack, etc.  These comparisons between CBOR and other binary formats were published by IETF:
- RFC 8949 CBOR, Appendix E: [Comparison of Other Binary Formats to CBOR's Design Objectives](https://www.rfc-editor.org/rfc/rfc8949.html#name-comparison-of-other-binary-)
- RFC 8618 Compacted-DNS, Appendix C: [Comparison of Binary Formats](https://www.rfc-editor.org/rfc/rfc8618#appendix-C)
=> Add IETF published comparisons between CBOR and other binary formats

ccf_specs.md
Make it more clear that:
1. some CCF requirements are defined as optional
2. CCF-based protocols can have their specs define how each CCF options is to be used
3.  it is outside the scope of this specification to define individual CCF-based protocols
More changes coming before tagging RC2.
=> Update ccf_specs.md for RC2 DRAFT

ccf_specs.md
Add more clarifications and improve text:
- Add "Scope" section to make it hard to miss.
- Mention CCF-based formats and protocols can have their specifications state how CCF options are used, which allows each protocol to balance their own tradeoffs like compatibility vs determinism vs speed vs encoded data size.
- Improve first half of "Introduction".
=> Update CCF Specifications to add Scope, etc.

ccf_specs.md
Updates #92 
Reduced 2nd half of the Introduction to:
> This specification uses CBOR, an Internet Standard defined by IETF STD 94. CBOR is designed to be relevant for decades and is used by data formats and protocols such as W3C WebAuthn, C-DNS (IETF RFC 8618), COSE (IETF STD 96), CWT (IETF RFC 8392), etc.
=> Improve and shorten Introduction

ccf_specs.md
Update "Introduction" section to add:
> CCF uses CBOR and is designed to allow efficient detection and rejection of malformed messages without creating Cadence objects. This allows more costly checks for validity, etc. to be performed only on well-formed messages.
This aspect of CCF and CBOR helps reject malformed inputs quickly and with less memory.
=> Add more context in Introduction about efficient rejection of malformed inputs

ccf_specs.md
Update CDDL in the specs to add new Cadence types and values:
- Added any-struct-attachment-type
- Added any-resource-attachment-type
- Added id-capability-value
- Renamed capability-value to path-capability-value
- Added word128-value and its type
- Added word256-value and its type
=> Add new Cadence types and values to CDDL

ccf_specs.md
Updates #92 
This is mostly to avoid confusion by bumping revision to 20230804a which was missed in prior PR.
While at it, add a sentence to "Interoperabilitty and Reuse of CBOR Codecs".
=> Update status from "RC2 DRAFT" to "RC2"

ccf_specs.md
Updates #92 
Update "Interoperability and Reuse of CBOR Codecs" about fxamacker/cbor:
- shorten list of companies using it.
- delete mention of GitHub report.
- add bullet point to mention it is maintained by author of this document.
=> Update "Interoperability and Reuse"

ccf_specs.md
I recently started updating https://github.com/onflow/ccf (in PR 7) to improve readability, explicitly state some things that might not be obvious to all readers, and fix grammar.
This syncs with latest commit in that PR (as of March 27, 2025).
Next, I'm going to update the "CCF Examples" section to be clearer.
=> Sync with onflow/ccf unmerged PR 7 commit 6703acb

ccf_specs.md
Improve text for readability:
These changes do not affect the current CCF codec implementation.
Improvements to "CCF Examples" section will be done in a separate PR (when time allows).
=> Improve text for CCF Specification 1.0.0
